// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuggestorCodeFirstAPI;

namespace SuggestorCodeFirstAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.Cancellation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ReservationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ReservationID")
                        .IsUnique()
                        .HasFilter("[ReservationID] IS NOT NULL");

                    b.HasIndex("UserID");

                    b.ToTable("Cancellations");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.EventPlannerService", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdultTickets")
                        .HasColumnType("int");

                    b.Property<string>("Audience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgURL02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgURL03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KidTickets")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerKid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("EventPlannerServices");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.EventPlannerServiceComment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EventPlannerServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("EventPlannerServiceID");

                    b.HasIndex("UserID");

                    b.ToTable("EventPlannerServiceComments");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.EventPlannerServiceRating", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventPlannerServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("EventPlannerServiceID");

                    b.HasIndex("UserID");

                    b.ToTable("EventPlannerServiceRatings");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HashTag", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HashTags");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HotelServiceRoomType", b =>
                {
                    b.Property<Guid?>("HotelServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HotelsServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HotelServiceId", "RoomTypeId");

                    b.HasIndex("HotelsServiceID");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("HotelServiceRoomTypes");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HotelsService", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltPnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfRooms")
                        .HasColumnType("int");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomImgURL01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomImgURL02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomImgURL03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("HotelsServices");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HotelsServiceComment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HotelsServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("HotelsServiceID");

                    b.HasIndex("UserID");

                    b.ToTable("HotelsServiceComments");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HotelsServiceRating", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HotelsServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("HotelsServiceID");

                    b.HasIndex("UserID");

                    b.ToTable("HotelsServiceRatings");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.Payment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.PostHashTags", b =>
                {
                    b.Property<Guid?>("EventPlannerServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HashTagID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventPlannerServiceID", "HashTagID");

                    b.HasIndex("HashTagID");

                    b.ToTable("PostHashTags");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.Reservation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfTravellers")
                        .HasColumnType("int");

                    b.Property<Guid?>("PaymentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("UserID");

                    b.ToTable("Reservations");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Reservation");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.RoomType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("Specs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RoomTypes");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TourGuideService", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("TourGuideServices");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TourGuideServiceComment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TourGuideServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("TourGuideServiceID");

                    b.HasIndex("UserID");

                    b.ToTable("TourGuideServiceComments");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TourGuideServiceRating", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("TourGuideServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("TourGuideServiceID");

                    b.HasIndex("UserID");

                    b.ToTable("TourGuideServiceRatings");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TransportService", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AirCondition")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOfSeats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PricePer1KM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("TransportServices");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TransportServiceComment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TransportServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("TransportServiceID");

                    b.HasIndex("UserID");

                    b.ToTable("TransportServiceComments");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TransportServiceRating", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransportServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("TransportServiceID");

                    b.HasIndex("UserID");

                    b.ToTable("TransportServiceRatings");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Address = "N0:198/3, Airport Road, Minuwangoda",
                            Contact = "0715510491",
                            DOB = "1996/07/27",
                            Email = "gdsudam@gmail.com",
                            FirstName = "Sudam",
                            LastName = "Yasodya",
                            Password = "123",
                            Role = "Admin",
                            Verified = false
                        },
                        new
                        {
                            ID = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991871"),
                            Address = "N0:198/3, Airport Road, Minuwangoda, Gampaha",
                            Contact = "0112294169",
                            DOB = "1996/07/28",
                            Email = "gdsudam@gmail.com.com",
                            FirstName = "Sudama",
                            LastName = "Yasodyaa",
                            Password = "1234",
                            Role = "Customer",
                            Verified = false
                        },
                        new
                        {
                            ID = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991875"),
                            Address = "N0:198/3, Airport Road, Malabe",
                            Contact = "071556223",
                            DOB = "1997/03/31",
                            Email = "rasmi@gmail.com",
                            FirstName = "Rasmi",
                            LastName = "Duli",
                            Password = "123123",
                            Role = "ServiceProvider",
                            Verified = false
                        });
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.EventPlannerServiceReservation", b =>
                {
                    b.HasBaseType("SuggestorCodeFirstAPI.Models.Reservation");

                    b.Property<int>("AdultTikets")
                        .HasColumnType("int");

                    b.Property<Guid?>("EventPlannerServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KidTikets")
                        .HasColumnType("int");

                    b.HasIndex("EventPlannerServiceID");

                    b.HasDiscriminator().HasValue("EventPlannerServiceReservation");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HotelsServiceReservation", b =>
                {
                    b.HasBaseType("SuggestorCodeFirstAPI.Models.Reservation");

                    b.Property<Guid?>("HotelsServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NoOfRooms")
                        .HasColumnType("int");

                    b.Property<string>("RoomType")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("HotelsServiceID");

                    b.HasDiscriminator().HasValue("HotelsServiceReservation");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TourGuideServiceReservation", b =>
                {
                    b.HasBaseType("SuggestorCodeFirstAPI.Models.Reservation");

                    b.Property<Guid?>("TourGuideServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("TourGuideServiceID");

                    b.HasDiscriminator().HasValue("TourGuideServiceReservation");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TransportServiceReservation", b =>
                {
                    b.HasBaseType("SuggestorCodeFirstAPI.Models.Reservation");

                    b.Property<string>("DropOffLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DropOffTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoOfPassengers")
                        .HasColumnType("int");

                    b.Property<string>("PickUpLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PickUpTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TransportServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("TransportServiceID");

                    b.HasDiscriminator().HasValue("TransportServiceReservation");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.Cancellation", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.Reservation", "Reservation")
                        .WithOne("Cancellation")
                        .HasForeignKey("SuggestorCodeFirstAPI.Models.Cancellation", "ReservationID");

                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("Cancellations")
                        .HasForeignKey("UserID");

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.EventPlannerService", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("EventPlannerServices")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.EventPlannerServiceComment", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.EventPlannerService", "EventPlannerService")
                        .WithMany("EventPlannerServiceComments")
                        .HasForeignKey("EventPlannerServiceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("EventPlannerServiceComment")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("EventPlannerService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.EventPlannerServiceRating", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.EventPlannerService", "EventPlannerService")
                        .WithMany("EventPlannerServiceRatings")
                        .HasForeignKey("EventPlannerServiceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("EventPlannerServiceRatings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("EventPlannerService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HotelServiceRoomType", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.HotelsService", "HotelsService")
                        .WithMany()
                        .HasForeignKey("HotelsServiceID");

                    b.HasOne("SuggestorCodeFirstAPI.Models.RoomType", "RoomType")
                        .WithMany("HotelServiceRoomTypes")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HotelsService");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HotelsService", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("HotelsServices")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HotelsServiceComment", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.HotelsService", "HotelsService")
                        .WithMany("HotelsServiceComments")
                        .HasForeignKey("HotelsServiceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("HotelsServiceComment")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HotelsService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HotelsServiceRating", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.HotelsService", "HotelsService")
                        .WithMany("HotelsServiceRatings")
                        .HasForeignKey("HotelsServiceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("HotelsServiceRatings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("HotelsService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.Payment", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.PostHashTags", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.EventPlannerService", "EventPlannerService")
                        .WithMany("PostHashTags")
                        .HasForeignKey("EventPlannerServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuggestorCodeFirstAPI.Models.HashTag", "HashTag")
                        .WithMany("PostHashTags")
                        .HasForeignKey("HashTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventPlannerService");

                    b.Navigation("HashTag");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.Reservation", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.Payment", "Payment")
                        .WithMany("Reservations")
                        .HasForeignKey("PaymentID");

                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserID");

                    b.Navigation("Payment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TourGuideService", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("TourGuideServices")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TourGuideServiceComment", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.TourGuideService", "TourGuideService")
                        .WithMany("TourGuideServiceComments")
                        .HasForeignKey("TourGuideServiceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("TourGuideServiceComments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TourGuideService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TourGuideServiceRating", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.TourGuideService", "TourGuideService")
                        .WithMany("TourGuideServiceRatings")
                        .HasForeignKey("TourGuideServiceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("TourGuideServiceRatings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TourGuideService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TransportService", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("TransportServices")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TransportServiceComment", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.TransportService", "TransportService")
                        .WithMany("TransportServiceComments")
                        .HasForeignKey("TransportServiceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("TransportServiceComments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TransportService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TransportServiceRating", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.TransportService", "TransportService")
                        .WithMany("TransportServiceRatings")
                        .HasForeignKey("TransportServiceID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SuggestorCodeFirstAPI.Models.User", "User")
                        .WithMany("TransportServiceRatings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("TransportService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.EventPlannerServiceReservation", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.EventPlannerService", "EventPlannerService")
                        .WithMany("EventPlannerServiceReservations")
                        .HasForeignKey("EventPlannerServiceID");

                    b.Navigation("EventPlannerService");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HotelsServiceReservation", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.HotelsService", "HotelsService")
                        .WithMany("HotelsServiceReservations")
                        .HasForeignKey("HotelsServiceID");

                    b.Navigation("HotelsService");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TourGuideServiceReservation", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.TourGuideService", "TourGuideService")
                        .WithMany("TourGuideServiceReservations")
                        .HasForeignKey("TourGuideServiceID");

                    b.Navigation("TourGuideService");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TransportServiceReservation", b =>
                {
                    b.HasOne("SuggestorCodeFirstAPI.Models.TransportService", "TransportService")
                        .WithMany("TransportServiceReservations")
                        .HasForeignKey("TransportServiceID");

                    b.Navigation("TransportService");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.EventPlannerService", b =>
                {
                    b.Navigation("EventPlannerServiceComments");

                    b.Navigation("EventPlannerServiceRatings");

                    b.Navigation("EventPlannerServiceReservations");

                    b.Navigation("PostHashTags");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HashTag", b =>
                {
                    b.Navigation("PostHashTags");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.HotelsService", b =>
                {
                    b.Navigation("HotelsServiceComments");

                    b.Navigation("HotelsServiceRatings");

                    b.Navigation("HotelsServiceReservations");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.Payment", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.Reservation", b =>
                {
                    b.Navigation("Cancellation");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.RoomType", b =>
                {
                    b.Navigation("HotelServiceRoomTypes");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TourGuideService", b =>
                {
                    b.Navigation("TourGuideServiceComments");

                    b.Navigation("TourGuideServiceRatings");

                    b.Navigation("TourGuideServiceReservations");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.TransportService", b =>
                {
                    b.Navigation("TransportServiceComments");

                    b.Navigation("TransportServiceRatings");

                    b.Navigation("TransportServiceReservations");
                });

            modelBuilder.Entity("SuggestorCodeFirstAPI.Models.User", b =>
                {
                    b.Navigation("Cancellations");

                    b.Navigation("EventPlannerServiceComment");

                    b.Navigation("EventPlannerServiceRatings");

                    b.Navigation("EventPlannerServices");

                    b.Navigation("HotelsServiceComment");

                    b.Navigation("HotelsServiceRatings");

                    b.Navigation("HotelsServices");

                    b.Navigation("Reservations");

                    b.Navigation("TourGuideServiceComments");

                    b.Navigation("TourGuideServiceRatings");

                    b.Navigation("TourGuideServices");

                    b.Navigation("TransportServiceComments");

                    b.Navigation("TransportServiceRatings");

                    b.Navigation("TransportServices");
                });
#pragma warning restore 612, 618
        }
    }
}
